twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categoryService: '@App\Service\CategoryService'
        cartService: '@App\Service\CartService'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
